### ISSUE TITLE
Updating package versions?

### ISSUE THREAD

**Issue by aspina7** [R4EPI/epireports#16]
Eventually need to work out what package versions need to be the minimum. 
Had error with dplyr on first install (old version and had to update)

**Comment by dirkschumacher** [comment]
What version was it?

**Comment by aspina7** [comment]
didnt check before running - there a way to check which version was on there before i installed epireports?

**Comment by zkamvar** [comment]
Not really unless you’ve got some Rmd output from before you updated that shows your sessionInfo

**Comment by dirkschumacher** [comment]
Can we close this issue?

**Comment by aspina7** [comment]
guess so - we will see if we get same issues when people trial it on fresh computers...
