### ISSUE TITLE
Nutrition zscore plots

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/epireports#21]
For nutrition surveys, we need plots that compare the observed z-scores to the WHO Standard. 

Expected output from an actual survey:
<img width="433" alt="screen shot 2019-01-11 at 13 09 22" src="https://user-images.githubusercontent.com/1569647/51036181-a1864400-15ac-11e9-860e-d0ec150f6320.png">

We should use ggplot2. Here is some quick sample code that uses the `anthro` package to generate the z-scores. But the function should really just take a vector of z-scores and necessary labels.

Quick illustration:
```R
library(ggplot2)
library(anthro)

n <- 1000
res <- anthro_zscores(sex = sample(c(1, 2), n, TRUE),
                  age = as.integer(rnorm(n, 1000, 3)),
                  lenhei = rnorm(n, 94, 3))


ggplot(res[res$flen == 0, ]) + 
  geom_density(aes(x = zlen), color = "darkred") + 
  stat_function(fun = dnorm, args = list(mean = 0, sd = 1), color = "darkgreen") +
  scale_x_continuous(limits = c(-6, 6))
```
<img width="489" alt="screen shot 2019-01-11 at 14 25 59" src="https://user-images.githubusercontent.com/1569647/51036267-de523b00-15ac-11e9-9cbc-6b47af050b72.png">

Please use colorblind and printer friendly colors

**Comment by dirkschumacher** [comment]
@aspina7 @thibautjombart @zkamvar I case you have some capacity.

**Comment by zkamvar** [comment]
On it!
