### ISSUE TITLE
Helper for statistic + CI

### ISSUE THREAD

**Issue by dirkschumacher** [R4EPI/epireports#7]
It is tedious to always write "x% CI (y-z)" within text. A helper function shall automate that

```R
str_rate(o = 5, n = 10, alpha = 0.05, method = "wilson")
str_odds(de = 5, dn =5, he = 10, hn = 5,  alpha = 0.05)
str_rr(de = 5, dn =5, he = 10, hn = 5,  alpha = 0.05)
# where de = disease exposed, dn = disease not exposed, 
# he = healthy exposed, hn = healthy not exposed
# variables names as on wikipedia
```

Used within markdown like this:

The CFR in Bamako is `r str_rate(o = 10, n = 50)`
=>
The CFR in Bamako is 20% (CI 11.24-33.04)

**Comment by zkamvar** [comment]
It may be a good idea to include a general function for just displaying in case a CI comes from another package:

```markdown
The CFR in Bamako is `r str_ci(e = cfr$rate, l = cfr$lower, u = cfr$upper)`
```
The CFR in Bamako is 20% (CI 11.24-33.04)
